databases:
  - name: secure-web-app-db
    databaseName: secure_web_app
    user: secure_web_app_user

services:
  - type: web
    name: secure-web-app-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DRIVER
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: secure-web-app-db
          property: connectionString
      - key: PGSSLMODE
        value: require
      - key: FRONTEND_URL
        value: http://localhost:5173,https://secure-web-app-teal.vercel.app
      - key: UPLOADS_DIR
        value: ./uploads
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SSL_PORT
        value: 465
      - key: SMTP_FAMILY
        value: 4
      - key: ENCRYPTION_KEY
        sync: false
